syntax on                       " 语法支持

"common conf {{                 通用配置
set ai                          " 自动缩进
set bs=2                        " 在insert模式下用退格键删除
set showmatch                   " 代码匹配
set laststatus=2                " 总是显示状态行
set expandtab                   " 以下三个配置配合使用，设置tab和缩进空格数
set shiftwidth=4
set tabstop=4
set cursorline                  " 为光标所在行加下划线
set number                      " 显示行号
set autoread                    " 文件在Vim之外修改过，自动重新载入

set ignorecase                  " 检索时忽略大小写
set fileencodings=utf-8,gbk     " 使用utf-8或gbk打开文件
set hls                         " 检索时高亮显示匹配项
set foldmethod=syntax           " 代码折叠
"set helplang=cn                " 将帮助系统设置为中文
"}}

"tabs conf {{                   " 标签页配置，通过ctrl-h/l切换标签等
let mapleader = ','
nnoremap <C-l> gt
nnoremap <C-h> gT
nnoremap <leader>t: tabe<CR>
"}}




"set autoindent
"set nu
"set smarttab


" filetype plugin on
autocmd FileType python set omnifunc=pythoncomplete#Complete


" Vundle Setting

set nocompatible              " be iMproved, required
filetype off                  " required

" http://www.erikzaadi.com/2012/03/19/auto-installing-vundle-from-your-vimrc/
" Setting up Vundle - the vim plugin bundler

let iCanHazVundle=1
let vundle_readme=expand('~/.vim/bundle/vundle/README.md')
if !filereadable(vundle_readme)
      echo "Installing Vundle.."
      echo ""
      silent !mkdir -p ~/.vim/bundle
      silent !git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
      let iCanHazVundle=0
endif

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/vundle
call vundle#begin()

Plugin 'scrooloose/nerdtree'

call vundle#end()            " required
filetype plugin indent on    " required


"plugins conf {{                " 插件配置


"}}